# Generated by Django 5.0.3 on 2024-04-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_remove_book_author_name_remove_book_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.CharField(choices=[('HC', 'Hard cover'), ('SC', 'Soft cover'), ('SPC', 'Special cover')], default='SC', max_length=3, verbose_name='cover type'),
        ),
    ]
